//categories
export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";

//comments
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const INCREMENT_COMMENT_SCORE = "INCREMENT_COMMENT_SCORE";
export const DECREMENT_COMMENT_SCORE = "DECREMENT_COMMENT_SCORE";
export const EDIT_COMMENT_BODY = "EDIT_COMMENT_BODY";
export const ADD_NEW_COMMENT = "ADD_NEW_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

//posts
export const RECEIVE_POSTS = "RECEIVE_POSTS";
export const GET_POSTS_BY_CATEGORY = "GET_POSTS_BY_CATEGORY";
export const INCREMENT_VOTE_SCORE = "INCREMENT_VOTE_SCORE";
export const DECREMENT_VOTE_SCORE = "DECREMENT_VOTE_SCORE";
export const ADD_NEW_POST = "ADD_NEW_POST";
export const GET_POST = "GET_POST";
export const EDIT_POST = "EDIT_POST";
export const DELETE_POST = "DELETE_POST";
export const SORT_BY_DATE = "SORT_BY_DATE";
export const SORT_BY_SCORE = "SORT_BY_SCORE";
